//! Tag writes into containers that are not MP3.
//!
//! Until this branch, `write_tag_fields` handed everything to the `id3` crate,
//! so a FLAC or an Ogg came back with an ID3v2 header bolted to the front and
//! no longer began with its own magic. Routing by container fixed that, and
//! `src/id3_editor.rs` has a thorough round-trip covering eleven formats, but
//! it is `#[ignore]`d behind a `SPARKAMP_FIXTURES` directory the caller has to
//! build with ffmpeg. Nothing about the routing runs in a plain `cargo test`.
//!
//! These do. Two real files, a tenth of a second of a sine tone each, small
//! enough to live in the repository and complete enough to have audio frames
//! after the tag block, which is what a bad write damages.
//!
//! Each check reads back through something other than the code that wrote:
//! `metaflac` for the FLAC comment, and Symphonia for whether the audio still
//! parses. A write that produced a plausible tag while corrupting the stream
//! would satisfy our own reader and fail these.

use std::path::{Path, PathBuf};

use sparkamp::id3_editor::{is_taggable, read_tag_fields, supports_field, write_tag_fields, TagFields};

/// Copy a fixture into a temporary directory, because these tests write.
fn scratch_copy(name: &str) -> (tempfile::TempDir, PathBuf) {
    let src = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    let dir = tempfile::tempdir().expect("temp dir");
    let dst = dir.path().join(name);
    std::fs::copy(&src, &dst).unwrap_or_else(|e| panic!("copying {}: {e}", src.display()));
    (dir, dst)
}

/// The first four bytes, which is where a prepended foreign tag shows up.
fn magic(path: &Path) -> [u8; 4] {
    let bytes = std::fs::read(path).expect("readable fixture");
    bytes[..4].try_into().expect("fixture shorter than 4 bytes")
}

#[test]
fn writing_a_flac_tag_keeps_the_container_and_the_audio() {
    let (_dir, flac) = scratch_copy("tone.flac");
    assert_eq!(&magic(&flac), b"fLaC", "fixture is not a FLAC to begin with");
    let duration_before = sparkamp::duration_probe::probe_duration(&flac);
    assert!(
        duration_before.is_some(),
        "fixture has no readable duration, so a later loss would prove nothing"
    );

    let mut fields = read_tag_fields(&flac);
    fields.title = "Tone Title".to_string();
    fields.artist = "Tone Artist".to_string();
    write_tag_fields(&flac, &fields).expect("writing a FLAC tag");

    assert_eq!(
        &magic(&flac),
        b"fLaC",
        "an ID3 tag was prepended; the write went through the MPEG path"
    );

    // metaflac, not our reader: the value has to be a real Vorbis comment.
    let tag = metaflac::Tag::read_from_path(&flac).expect("still a readable FLAC");
    let title: Vec<&str> = tag.get_vorbis("TITLE").into_iter().flatten().collect();
    assert_eq!(
        title,
        vec!["Tone Title"],
        "TITLE is not a Vorbis comment in the FLAC's own metadata block"
    );

    assert_eq!(
        sparkamp::duration_probe::probe_duration(&flac),
        duration_before,
        "the audio frames did not survive the tag write"
    );
}

#[test]
fn writing_an_ogg_tag_keeps_the_container_and_the_audio() {
    let (_dir, ogg) = scratch_copy("tone.ogg");
    assert_eq!(&magic(&ogg), b"OggS", "fixture is not an Ogg to begin with");
    let duration_before = sparkamp::duration_probe::probe_duration(&ogg);
    assert!(
        duration_before.is_some(),
        "fixture has no readable duration, so a later loss would prove nothing"
    );

    let mut fields = read_tag_fields(&ogg);
    fields.title = "Tone Title".to_string();
    fields.artist = "Tone Artist".to_string();
    write_tag_fields(&ogg, &fields).expect("writing an Ogg tag");

    assert_eq!(
        &magic(&ogg),
        b"OggS",
        "an ID3 tag was prepended; the write went through the MPEG path"
    );

    // Symphonia demuxes the Ogg pages independently of lofty. A write that
    // broke the page structure fails here even if a tag reads back.
    assert_eq!(
        sparkamp::duration_probe::probe_duration(&ogg),
        duration_before,
        "the Ogg stream did not survive the tag write"
    );

    let back = read_tag_fields(&ogg);
    assert_eq!(back.title, "Tone Title");
    assert_eq!(back.artist, "Tone Artist");
}

/// Every container Sparkamp supports, as generated by `tools/make-test-tones.sh`.
/// Monkey's Audio and Musepack are absent: neither has an encoder available, so
/// there is no fixture to test against rather than a decision to skip them.
const CONTAINERS: &[&str] = &[
    "mp3", "flac", "ogg", "opus", "wav", "aac", "m4a", "wma", "tta", "wv", "aiff",
];

/// The capability gate must not lie.
///
/// `supports_field` decides whether the editor offers a row at all, so a field
/// it calls storable has to survive a write and a read. A false yes is worse
/// than a false no: the user types a value, saves, and the value is gone with
/// no error, which is exactly the failure the gate was added to prevent.
///
/// The converse is deliberately not asserted here. A field the gate refuses may
/// still be storable in principle, and where that is true it is a mapping gap
/// worth closing rather than a lie worth failing the build over.
#[test]
fn a_field_the_gate_calls_storable_survives_a_write() {
    let mut liars: Vec<String> = Vec::new();

    for ext in CONTAINERS {
        let name = format!("tone.{ext}");
        let (_dir, path) = scratch_copy(&name);
        if !is_taggable(&path) {
            // WMA and friends have no writable tag format; the editor shows an
            // empty state for these rather than a form.
            continue;
        }

        let claimed: Vec<&str> = TagFields::field_ids()
            .into_iter()
            .filter(|id| supports_field(&path, id))
            .collect();

        // Twice, with different values. Tagging a fresh file and editing a file
        // that already carries tags are different code paths through lofty, and
        // only the second one rewrites an existing tag. Users do the second far
        // more often than the first.
        for (pass, salt) in [(1, 10), (2, 20)] {
            // One distinct value per field, so a value landing on the wrong
            // field shows up as a mismatch rather than passing by coincidence.
            let mut fields = read_tag_fields(&path);
            for (i, id) in claimed.iter().enumerate() {
                // Numeric fields are parsed on the way out, so they get digits.
                let value = match *id {
                    "year" => format!("{}", 1990 + pass),
                    "track_num" | "track_total" | "disc_num" | "disc_total" | "bpm" => {
                        format!("{}", i + salt)
                    }
                    _ => format!("value {i} pass {pass}"),
                };
                *fields.value_mut(id).expect("known id") = value;
            }
            write_tag_fields(&path, &fields)
                .unwrap_or_else(|e| panic!("{ext}: write on pass {pass} failed: {e}"));

            let back = read_tag_fields(&path);
            for id in &claimed {
                let want = fields.value(id).unwrap();
                let got = back.value(id).unwrap();
                if want != got {
                    liars.push(format!(
                        "  {ext} {id} (pass {pass}): claimed storable, wrote {want:?}, \
                         read back {got:?}"
                    ));
                }
            }
        }
    }

    assert!(
        liars.is_empty(),
        "the capability gate promised fields these containers did not keep:\n{}",
        liars.join("\n")
    );
}

/// BPM and lyrics reach the containers that can hold them.
///
/// Both were silently dropped before the field-to-key mapping stopped going
/// through ID3. BPM asked for `IntegerBpm`, which lofty documents as ID3v2 and
/// MP4 only, so every Vorbis container lost it despite `BPM` being a standard
/// Vorbis field. Lyrics asked for `Lyrics`, which lofty deliberately does not
/// map for ID3v2, so a WAV or AIFF carrying an ID3 chunk lost those.
///
/// This is the half the honesty test cannot check: it would also pass if the
/// editor simply stopped offering the fields.
#[test]
fn bpm_and_lyrics_reach_the_containers_that_hold_them() {
    for ext in ["flac", "ogg", "opus"] {
        let (_dir, path) = scratch_copy(&format!("tone.{ext}"));
        assert!(
            supports_field(&path, "bpm"),
            "{ext} can hold a BPM: it is a standard Vorbis comment field"
        );
        let mut f = read_tag_fields(&path);
        f.bpm = "128".into();
        write_tag_fields(&path, &f).unwrap();
        assert_eq!(read_tag_fields(&path).bpm, "128", "{ext} lost the BPM");
    }

    for ext in ["wav", "aiff"] {
        let (_dir, path) = scratch_copy(&format!("tone.{ext}"));
        assert!(supports_field(&path, "lyric"), "{ext} carries an ID3 tag");
        let mut f = read_tag_fields(&path);
        f.lyric = "a line of lyrics".into();
        write_tag_fields(&path, &f).unwrap();
        assert_eq!(
            read_tag_fields(&path).lyric,
            "a line of lyrics",
            "{ext} lost the lyrics"
        );
    }
}
