// AUTO-GENERATED by tools/embed-skin-guide.sh — do not edit.
// Source of truth: src/skin_templates/skin-guide.md
//
// Re-run the script (or rebuild in Xcode with the Run Script phase wired up)
// after editing the markdown file. The script is idempotent.

import Foundation

extension ThemeManager {
    /// Embedded copy of the user-facing skin authoring guide.
    /// Exported by Settings → Appearance → Export how-to guide…
    static let skinGuideMD: String = ##"""
# Sparkamp Skin Guide

## What a skin is

A Sparkamp skin is a single `.css` file declaring 14 variables inside a
`:root { }` block. The same file drives Sparkamp's appearance identically
on Linux (GTK4) and macOS.

## Creating your first skin

1. In Settings → Appearance, select Dark or Light.
2. Click **Download skin…** and save it as e.g. `mytheme.css`.
3. Open the file in any text editor.
4. Edit the values inside the `:root { }` block.
5. In Settings → Appearance, click **Add skin…** and pick your file.

The skin applies immediately. To switch, click a different row in the
skin list.

## The 14 variables

### Colors

**`--sp-background`** — `#rgb` or `#rrggbb`
The window chrome behind everything else.
- Main player window frame
- Media Library window frame (outside the listview)
- Settings, ID3 Editor, Dedupe, Artwork, Keyboard Shortcuts, Jump to
  Track, Information, Equalizer window frames

**`--sp-text-background`** — `#rgb` or `#rrggbb`
The "panel" color — darker/contrasting areas that hold text.
- Marquee panel (now-playing title and artist area)
- Time display background
- Playlist scrollable area
- Media Library listview area
- Settings / ID3 Editor input fields and text boxes

**`--sp-text-color`** — `#rgb` or `#rrggbb`
All body text, on both `background` and `text-background` surfaces.
- Marquee title, marquee artist, time digits
- Playlist rows, Media Library cells
- Settings labels, ID3 Editor field text
- Information window body, Jump window
- Keyboard Shortcuts, Dedupe, Artwork, Equalizer text

**`--sp-highlight`** — `#rgb` or `#rrggbb`
Selection, focus, and active-state accent.
- Currently-playing playlist row text
- Currently-selected list/table row background (~18% opacity)
- Active (toggled-on) mode buttons: shuffle, repeat, PL, Info
- Seek and volume bar fills
- Focus ring

**`--sp-broken-color`** — `#rgb` or `#rrggbb`
The warning color for missing/unplayable files.
- Playlist row text for a broken track
- Media Library row text for a broken track
- The `✗` prefix glyph in front of each broken row

### Buttons

**`--sp-button-color`** — resting state
**`--sp-button-hover`** — mouse over
**`--sp-button-active`** — toggled ON (only for toggle buttons: shuffle,
repeat, PL, Info)
**`--sp-button-pressed`** — being clicked right now (mouse held down)
**`--sp-button-text-color`** — icon / label on every button state

Applies to: transport buttons (prev / play / pause / stop / next), mode
toggle buttons, playlist buttons (Add / Remove / Clear), dialog buttons
across all windows.

### Fonts

**`--sp-font-family`** — CSS font-family string
Applies to all text except time digits (which are always monospace).
Example: `"Inter, Helvetica, sans-serif"`. The first installed family wins.

**`--sp-font-size`** — e.g. `12px`
Applies to: playlist rows, ML cells, settings labels, ID3 editor, Jump,
Information, Keyboard Shortcuts, Dedupe, Artwork, Equalizer, all buttons,
volume %, status bar.

**`--sp-font-size-large`** — e.g. `32px`
Time index display only.

**`--sp-font-size-marquee`** — e.g. `14px`
Marquee title in the now-playing panel.

## Auto-derived (not user-facing)

These are computed in code; your skin does not set them directly:

- Selected row background — `highlight` at 18% opacity
- Playing row background — `highlight` at 10% opacity
- Hover row background — `highlight` at 8% opacity
- Seek / volume track background — `text-background`
- Seek / volume fill and thumb — `highlight`
- Muted / dim text (duration column, volume %) — `text-color` at 60% opacity
- Window and panel borders — `background` luminance ±8%
- Time-digit font family — hardcoded monospace

## Tips

- Keep `text-color` and `text-background` at high contrast for readability.
- `highlight` should be visually distinct from both `text-color` and
  `text-background` (it colors text in some places and backgrounds in others).
- Order button state colors perceptually: `color` → `hover` → `pressed`
  so clicks feel responsive. `active` can be a different hue entirely
  (the spec uses an accent-tinted color).

## Limits

This basic template is about colors, fonts, and sizes. It does not
support structural changes (paddings, margins, window sizes, corner
radii) or images. An advanced template with fine-grained overrides and
button image packs is planned for a later release.
"""##
}
