#!/usr/bin/env bash
# embed-skin-guide.sh — Generate Theme+Guide.swift from the canonical
# skin-guide.md so the macOS app can ship the same documentation that the
# Rust core embeds into Linux skin exports. Single source of truth: the
# markdown file under src/skin_templates/.
#
# Usage:
#   ./tools/embed-skin-guide.sh           # uses repo-relative paths
#   ./tools/embed-skin-guide.sh SRC DEST  # explicit input + output paths
#
# Intended to run as an Xcode "Run Script" build phase placed before
# "Compile Sources". Idempotent — safe to run from the command line at any
# time; the generated file is checked in so the project also builds without
# the script (e.g. clean checkout opened in Xcode before first build).

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

SRC="${1:-$REPO_ROOT/src/skin_templates/skin-guide.md}"
DEST="${2:-$REPO_ROOT/frontends/SparkampMac/Sources/Theme+Guide.swift}"

if [[ ! -f "$SRC" ]]; then
    echo "embed-skin-guide.sh: source not found: $SRC" >&2
    exit 1
fi

# Use a Swift extended raw string ##"""..."""## so the markdown body needs
# zero escaping. (It would only collide if the guide ever contains the
# literal sequence `"""##`, which it does not.)
TMP="$(mktemp)"
{
    echo '// AUTO-GENERATED by tools/embed-skin-guide.sh — do not edit.'
    echo '// Source of truth: src/skin_templates/skin-guide.md'
    echo '//'
    echo '// Re-run the script (or rebuild in Xcode with the Run Script phase wired up)'
    echo '// after editing the markdown file. The script is idempotent.'
    echo ''
    echo 'import Foundation'
    echo ''
    echo 'extension ThemeManager {'
    echo '    /// Embedded copy of the user-facing skin authoring guide.'
    echo '    /// Exported by Settings → Appearance → Export how-to guide…'
    echo '    static let skinGuideMD: String = ##"""'
    cat "$SRC"
    echo '"""##'
    echo '}'
} > "$TMP"

# Only overwrite if content changed — keeps Xcode incremental builds fast.
if [[ ! -f "$DEST" ]] || ! cmp -s "$TMP" "$DEST"; then
    mv "$TMP" "$DEST"
    echo "embed-skin-guide.sh: wrote $DEST"
else
    rm "$TMP"
    echo "embed-skin-guide.sh: $DEST already up to date"
fi
